### PR TITLE
Update to latest

### PR DESCRIPTION
**Pull request by KozhinovAlexander**
Update CivetWeb to latest one from [here](https://github.com/civetweb/civetweb)

### CODE REVIEW

**Comment by KozhinovAlexander** [comment]
@jukkar @PiotrZierhoffer Please review it.

**Review by jukkar — APPROVED** [review]

**Review by PiotrZierhoffer — APPROVED** [review]

**Comment by KozhinovAlexander** [comment]
@PiotrZierhoffer Can you please trigger the person, who is able to merge?

**Comment by PiotrZierhoffer** [comment]
@Nukersson I was about to do it, but we have incompatible histories. I suggest we actually PR the websocket support in Zephyr to upstream civetweb and then merge with upstream. Do you agree? I can do it, but want to cross validate the idea, as it's very late and I don't want to do something irreversible

**Comment by KozhinovAlexander** [comment]
> @Nukersson I was about to do it, but we have incompatible histories. I suggest we actually PR the websocket support in Zephyr to upstream civetweb and then merge with upstream. Do you agree? I can do it, but want to cross validate the idea, as it's very late and I don't want to do something irreversible 

@PiotrZierhoffer Thank you. I am totally agree with your proposal and would be happy, if you can do it.

**Comment by PiotrZierhoffer** [comment]
I created a PR here: https://github.com/civetweb/civetweb/pull/946

**Comment by KozhinovAlexander** [comment]
@PiotrZierhoffer Hello Piotr. Looks like "civetweb: WebSockets support for Zephyr #946" is merged now. What is the next step?

**Comment by PiotrZierhoffer** [comment]
I pushed -f to your branch and got it merged.

**Pull request merged**
